### PR TITLE
check for presence of secrets directory in git ignore + tag support

### PR DESCRIPTION
**Pull request by otakup0pe**
Addresses #10, #12, #19 

Ignore the name of the branch 😊

### CODE REVIEW

**Comment by otakup0pe** [comment]
Added some tests for @shaiguitar 🎸

**Comment by otakup0pe** [comment]
Also the tests will now try and preserve your `~/.vault-token` if it exists.

**Comment by shaiguitar** [comment]
:8ball:

**Comment by otakup0pe** [comment]
i'll take it

**Pull request merged**
